djangoproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('training.urls'), name='home'),
    path('training/', include('training.urls'), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/login/', TemplateView.as_view(template_name='login.html'), name='login')
]

training/urls.py
from django.urls import path

from . import views

app_name = 'training'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

training/models.py
# Create your models here.
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

training/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from training.models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'training/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'training/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'training/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'training/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('training:results', args=(question.id,)))

templates/base.html
<!--This is base html template for other pages such as login.html-->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'training/style.css' %}">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

training/templates/training/detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'training/style.css' %}">
<title>Poll Details</title>

<button class="btn"><a href="{% url 'training:index' %}">Home</a></button>
<!--If else condition to determine which button will be display-->
{% if user.is_authenticated %}
    <button class="btn" ><a href="{% url 'logout' %}">Log Out</a></button>
{% else %}
      <button class="btn"><a href="{% url 'login' %}">Log In</a></button>
{% endif %}

<h1>Poll's Details</h1>
<!--Form to create a new vote for a certain question -->
<form action="{% url 'training:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

training/templates/training/index.html
{% load static %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'training/style.css' %}">
<title>Polls</title>

{% block content %}
{% if user.is_authenticated %}
  <div class="login_logout">
      <h3><strong>Hi {{ user.username }}!</strong></h3>
      <button class="btn" ><a href="{% url 'logout' %}">Log Out</a></button>
  </div>
{% else %}
  <div class="login_logout">
      <h3><strong>You are not logged in</strong></h3>
      <button class="btn"><a href="{% url 'login' %}">Log In</a></button>
  </div>
{% endif %}
{% endblock %}

<h1>Let's let the Polls decide it {;-)</h1>
<div class="borders">
    {% if latest_question_list %}
        <ol>
            <!--Loop to display all pools-->
            {% for question in latest_question_list %}
                <li><a href="{% url 'training:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</div>

training/templates/training/results.html
{% load static %}

<link rel="stylesheet" href="{% static 'training/style.css' %}">
<title>Poll Results</title>

<button class="btn"><a href="{% url 'training:index' %}">Home</a></button>
<button class="btn"><a href="{% url 'training:detail' question.id %}">Vote Again</a></button>
{% if user.is_authenticated %}
    <button class="btn" ><a href="{% url 'logout' %}">Log Out</a></button>
{% else %}
      <button class="btn"><a href="{% url 'login' %}">Log In</a></button>
{% endif %}

<h1>Poll's Result</h1>
<div class="borders">
    <h1>{{ question.question_text }}</h1>
    <div>
        <ul>
            <!--Loop to display all polls choices-->
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
        </ul>
    </div>
</div>